/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as EvalsIndexRouteImport } from './routes/evals/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as TasksTaskKeyRouteImport } from './routes/tasks/$taskKey'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as McpServerIdRouteImport } from './routes/mcp/$serverId'
import { Route as EvalsEvalIdRouteImport } from './routes/evals/$evalId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as InventorySystemPromptsIndexRouteImport } from './routes/inventory/system-prompts/index'
import { Route as InventoryAgentsIndexRouteImport } from './routes/inventory/agents/index'
import { Route as ApiTracesIndexRouteImport } from './routes/api/traces/index'
import { Route as InventorySystemPromptsPromptIdRouteImport } from './routes/inventory/system-prompts/$promptId'
import { Route as EvalsRunsRunIdRouteImport } from './routes/evals/runs.$runId'
import { Route as ApiEvalsIngestRouteImport } from './routes/api/evals/ingest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTracesTraceIdIndexRouteImport } from './routes/api/traces/$traceId/index'
import { Route as ApiSessionsSessionIdIndexRouteImport } from './routes/api/sessions/$sessionId/index'
import { Route as ApiTracesTraceIdConversationRouteImport } from './routes/api/traces/$traceId/conversation'
import { Route as ApiTracesTraceIdBriefRouteImport } from './routes/api/traces/$traceId/brief'
import { Route as ApiSessionsSessionIdBriefRouteImport } from './routes/api/sessions/$sessionId/brief'
import { Route as ApiTracesTraceIdSpansSpanIdRouteImport } from './routes/api/traces/$traceId/spans/$spanId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskKeyRoute = TasksTaskKeyRouteImport.update({
  id: '/tasks/$taskKey',
  path: '/tasks/$taskKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServerIdRoute = McpServerIdRouteImport.update({
  id: '/mcp/$serverId',
  path: '/mcp/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsEvalIdRoute = EvalsEvalIdRouteImport.update({
  id: '/evals/$evalId',
  path: '/evals/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySystemPromptsIndexRoute =
  InventorySystemPromptsIndexRouteImport.update({
    id: '/inventory/system-prompts/',
    path: '/inventory/system-prompts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryAgentsIndexRoute = InventoryAgentsIndexRouteImport.update({
  id: '/inventory/agents/',
  path: '/inventory/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracesIndexRoute = ApiTracesIndexRouteImport.update({
  id: '/api/traces/',
  path: '/api/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySystemPromptsPromptIdRoute =
  InventorySystemPromptsPromptIdRouteImport.update({
    id: '/inventory/system-prompts/$promptId',
    path: '/inventory/system-prompts/$promptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvalsRunsRunIdRoute = EvalsRunsRunIdRouteImport.update({
  id: '/evals/runs/$runId',
  path: '/evals/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvalsIngestRoute = ApiEvalsIngestRouteImport.update({
  id: '/api/evals/ingest',
  path: '/api/evals/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracesTraceIdIndexRoute = ApiTracesTraceIdIndexRouteImport.update({
  id: '/api/traces/$traceId/',
  path: '/api/traces/$traceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdIndexRoute =
  ApiSessionsSessionIdIndexRouteImport.update({
    id: '/api/sessions/$sessionId/',
    path: '/api/sessions/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTracesTraceIdConversationRoute =
  ApiTracesTraceIdConversationRouteImport.update({
    id: '/api/traces/$traceId/conversation',
    path: '/api/traces/$traceId/conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTracesTraceIdBriefRoute = ApiTracesTraceIdBriefRouteImport.update({
  id: '/api/traces/$traceId/brief',
  path: '/api/traces/$traceId/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdBriefRoute =
  ApiSessionsSessionIdBriefRouteImport.update({
    id: '/api/sessions/$sessionId/brief',
    path: '/api/sessions/$sessionId/brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTracesTraceIdSpansSpanIdRoute =
  ApiTracesTraceIdSpansSpanIdRouteImport.update({
    id: '/api/traces/$traceId/spans/$spanId',
    path: '/api/traces/$traceId/spans/$spanId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/mcp/$serverId': typeof McpServerIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/api/': typeof ApiIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/api/traces/': typeof ApiTracesIndexRoute
  '/inventory/agents/': typeof InventoryAgentsIndexRoute
  '/inventory/system-prompts/': typeof InventorySystemPromptsIndexRoute
  '/api/sessions/$sessionId/brief': typeof ApiSessionsSessionIdBriefRoute
  '/api/traces/$traceId/brief': typeof ApiTracesTraceIdBriefRoute
  '/api/traces/$traceId/conversation': typeof ApiTracesTraceIdConversationRoute
  '/api/sessions/$sessionId/': typeof ApiSessionsSessionIdIndexRoute
  '/api/traces/$traceId/': typeof ApiTracesTraceIdIndexRoute
  '/api/traces/$traceId/spans/$spanId': typeof ApiTracesTraceIdSpansSpanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/mcp/$serverId': typeof McpServerIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/api': typeof ApiIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/evals': typeof EvalsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/mcp': typeof McpIndexRoute
  '/notes': typeof NotesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/traces': typeof TracesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/api/traces': typeof ApiTracesIndexRoute
  '/inventory/agents': typeof InventoryAgentsIndexRoute
  '/inventory/system-prompts': typeof InventorySystemPromptsIndexRoute
  '/api/sessions/$sessionId/brief': typeof ApiSessionsSessionIdBriefRoute
  '/api/traces/$traceId/brief': typeof ApiTracesTraceIdBriefRoute
  '/api/traces/$traceId/conversation': typeof ApiTracesTraceIdConversationRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdIndexRoute
  '/api/traces/$traceId': typeof ApiTracesTraceIdIndexRoute
  '/api/traces/$traceId/spans/$spanId': typeof ApiTracesTraceIdSpansSpanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/mcp/$serverId': typeof McpServerIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/api/': typeof ApiIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/api/traces/': typeof ApiTracesIndexRoute
  '/inventory/agents/': typeof InventoryAgentsIndexRoute
  '/inventory/system-prompts/': typeof InventorySystemPromptsIndexRoute
  '/api/sessions/$sessionId/brief': typeof ApiSessionsSessionIdBriefRoute
  '/api/traces/$traceId/brief': typeof ApiTracesTraceIdBriefRoute
  '/api/traces/$traceId/conversation': typeof ApiTracesTraceIdConversationRoute
  '/api/sessions/$sessionId/': typeof ApiSessionsSessionIdIndexRoute
  '/api/traces/$traceId/': typeof ApiTracesTraceIdIndexRoute
  '/api/traces/$traceId/spans/$spanId': typeof ApiTracesTraceIdSpansSpanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/chat'
    | '/api/search'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/mcp/$serverId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/api/'
    | '/changelog/'
    | '/datasets/'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/notes/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/traces/'
    | '/api/auth/$'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/api/traces/'
    | '/inventory/agents/'
    | '/inventory/system-prompts/'
    | '/api/sessions/$sessionId/brief'
    | '/api/traces/$traceId/brief'
    | '/api/traces/$traceId/conversation'
    | '/api/sessions/$sessionId/'
    | '/api/traces/$traceId/'
    | '/api/traces/$traceId/spans/$spanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/chat'
    | '/api/search'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/mcp/$serverId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/api'
    | '/changelog'
    | '/datasets'
    | '/evals'
    | '/inbox'
    | '/mcp'
    | '/notes'
    | '/sessions'
    | '/tasks'
    | '/tools'
    | '/traces'
    | '/api/auth/$'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/api/traces'
    | '/inventory/agents'
    | '/inventory/system-prompts'
    | '/api/sessions/$sessionId/brief'
    | '/api/traces/$traceId/brief'
    | '/api/traces/$traceId/conversation'
    | '/api/sessions/$sessionId'
    | '/api/traces/$traceId'
    | '/api/traces/$traceId/spans/$spanId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/chat'
    | '/api/search'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/mcp/$serverId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/api/'
    | '/changelog/'
    | '/datasets/'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/notes/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/traces/'
    | '/api/auth/$'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/api/traces/'
    | '/inventory/agents/'
    | '/inventory/system-prompts/'
    | '/api/sessions/$sessionId/brief'
    | '/api/traces/$traceId/brief'
    | '/api/traces/$traceId/conversation'
    | '/api/sessions/$sessionId/'
    | '/api/traces/$traceId/'
    | '/api/traces/$traceId/spans/$spanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  EvalsEvalIdRoute: typeof EvalsEvalIdRoute
  McpServerIdRoute: typeof McpServerIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TasksTaskKeyRoute: typeof TasksTaskKeyRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEvalsIngestRoute: typeof ApiEvalsIngestRoute
  EvalsRunsRunIdRoute: typeof EvalsRunsRunIdRoute
  InventorySystemPromptsPromptIdRoute: typeof InventorySystemPromptsPromptIdRoute
  ApiTracesIndexRoute: typeof ApiTracesIndexRoute
  InventoryAgentsIndexRoute: typeof InventoryAgentsIndexRoute
  InventorySystemPromptsIndexRoute: typeof InventorySystemPromptsIndexRoute
  ApiSessionsSessionIdBriefRoute: typeof ApiSessionsSessionIdBriefRoute
  ApiTracesTraceIdBriefRoute: typeof ApiTracesTraceIdBriefRoute
  ApiTracesTraceIdConversationRoute: typeof ApiTracesTraceIdConversationRoute
  ApiSessionsSessionIdIndexRoute: typeof ApiSessionsSessionIdIndexRoute
  ApiTracesTraceIdIndexRoute: typeof ApiTracesTraceIdIndexRoute
  ApiTracesTraceIdSpansSpanIdRoute: typeof ApiTracesTraceIdSpansSpanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/evals'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskKey': {
      id: '/tasks/$taskKey'
      path: '/tasks/$taskKey'
      fullPath: '/tasks/$taskKey'
      preLoaderRoute: typeof TasksTaskKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$serverId': {
      id: '/mcp/$serverId'
      path: '/mcp/$serverId'
      fullPath: '/mcp/$serverId'
      preLoaderRoute: typeof McpServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/$evalId': {
      id: '/evals/$evalId'
      path: '/evals/$evalId'
      fullPath: '/evals/$evalId'
      preLoaderRoute: typeof EvalsEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/system-prompts/': {
      id: '/inventory/system-prompts/'
      path: '/inventory/system-prompts'
      fullPath: '/inventory/system-prompts/'
      preLoaderRoute: typeof InventorySystemPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/agents/': {
      id: '/inventory/agents/'
      path: '/inventory/agents'
      fullPath: '/inventory/agents/'
      preLoaderRoute: typeof InventoryAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/': {
      id: '/api/traces/'
      path: '/api/traces'
      fullPath: '/api/traces/'
      preLoaderRoute: typeof ApiTracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/system-prompts/$promptId': {
      id: '/inventory/system-prompts/$promptId'
      path: '/inventory/system-prompts/$promptId'
      fullPath: '/inventory/system-prompts/$promptId'
      preLoaderRoute: typeof InventorySystemPromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/runs/$runId': {
      id: '/evals/runs/$runId'
      path: '/evals/runs/$runId'
      fullPath: '/evals/runs/$runId'
      preLoaderRoute: typeof EvalsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evals/ingest': {
      id: '/api/evals/ingest'
      path: '/api/evals/ingest'
      fullPath: '/api/evals/ingest'
      preLoaderRoute: typeof ApiEvalsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/$traceId/': {
      id: '/api/traces/$traceId/'
      path: '/api/traces/$traceId'
      fullPath: '/api/traces/$traceId/'
      preLoaderRoute: typeof ApiTracesTraceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/': {
      id: '/api/sessions/$sessionId/'
      path: '/api/sessions/$sessionId'
      fullPath: '/api/sessions/$sessionId/'
      preLoaderRoute: typeof ApiSessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/$traceId/conversation': {
      id: '/api/traces/$traceId/conversation'
      path: '/api/traces/$traceId/conversation'
      fullPath: '/api/traces/$traceId/conversation'
      preLoaderRoute: typeof ApiTracesTraceIdConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/$traceId/brief': {
      id: '/api/traces/$traceId/brief'
      path: '/api/traces/$traceId/brief'
      fullPath: '/api/traces/$traceId/brief'
      preLoaderRoute: typeof ApiTracesTraceIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/brief': {
      id: '/api/sessions/$sessionId/brief'
      path: '/api/sessions/$sessionId/brief'
      fullPath: '/api/sessions/$sessionId/brief'
      preLoaderRoute: typeof ApiSessionsSessionIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traces/$traceId/spans/$spanId': {
      id: '/api/traces/$traceId/spans/$spanId'
      path: '/api/traces/$traceId/spans/$spanId'
      fullPath: '/api/traces/$traceId/spans/$spanId'
      preLoaderRoute: typeof ApiTracesTraceIdSpansSpanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSearchRoute: ApiSearchRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  EvalsEvalIdRoute: EvalsEvalIdRoute,
  McpServerIdRoute: McpServerIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TasksTaskKeyRoute: TasksTaskKeyRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  ApiIndexRoute: ApiIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  EvalsIndexRoute: EvalsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  McpIndexRoute: McpIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEvalsIngestRoute: ApiEvalsIngestRoute,
  EvalsRunsRunIdRoute: EvalsRunsRunIdRoute,
  InventorySystemPromptsPromptIdRoute: InventorySystemPromptsPromptIdRoute,
  ApiTracesIndexRoute: ApiTracesIndexRoute,
  InventoryAgentsIndexRoute: InventoryAgentsIndexRoute,
  InventorySystemPromptsIndexRoute: InventorySystemPromptsIndexRoute,
  ApiSessionsSessionIdBriefRoute: ApiSessionsSessionIdBriefRoute,
  ApiTracesTraceIdBriefRoute: ApiTracesTraceIdBriefRoute,
  ApiTracesTraceIdConversationRoute: ApiTracesTraceIdConversationRoute,
  ApiSessionsSessionIdIndexRoute: ApiSessionsSessionIdIndexRoute,
  ApiTracesTraceIdIndexRoute: ApiTracesTraceIdIndexRoute,
  ApiTracesTraceIdSpansSpanIdRoute: ApiTracesTraceIdSpansSpanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
